"""Write Nemotron's routed-expert decode kernels (rows.py, read with ast) as mx.fast.metal_kernel builds them."""

from __future__ import annotations

import argparse
import ast
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from metal_source import PREAMBLE, Arg, kernel_text, strip_comments  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
ROWS = ROOT / "src/tensorfold/kernels/nemotron/lightning/v1/rows.py"
OUT = ROOT / "zig/kernels/metal"

# Nemotron 3.5 Lightning 30B-A3B: hidden 2688, expert width 1856, 128 experts, top 6, 4-bit groups of 64
HIDDEN, EXPERT, EXPERTS, TOP_K, GROUP = 2688, 1856, 128, 6, 64
SIMDGROUPS = 2                  # rows.experts' default
TABLE = 8                       # pair tables padded to MIN_ELEMENTS, so they bind as device memory


def strings(path: Path) -> dict[str, str]:
    """Module-level string constants of `path`, following names and + between them."""

    found: dict[str, str] = {}

    def value(node: ast.AST) -> str | None:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        if isinstance(node, ast.Name):
            return found.get(node.id)
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
            left, right = value(node.left), value(node.right)
            return None if left is None or right is None else left + right
        return None

    for node in ast.parse(path.read_text()).body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            text = value(node.value)
            if text is not None:
                found[node.targets[0].id] = text
    return found


def kernels() -> list[dict]:
    """The expert kernels a 1-row step runs: name, inputs, outputs, template, grid and threadgroup as rows.py calls them."""

    s = strings(ROWS)
    header, rps = s["_HEADER"], 4
    out = []
    for kind, source, k, n, extra in (("up", s["_EXPERT_UP"], HIDDEN, EXPERT, [("TOPK", TOP_K)]),
                                      ("down", s["_EXPERT_DOWN"], EXPERT, HIDDEN, [])):
        base = f"nemotron_rows_expert_{kind}"
        name = f"{base}_{hashlib.sha256((header + source).encode()).hexdigest()[:16]}"
        inputs = [Arg("X", "bfloat16", 64), Arg("UIDS", "uint32", TABLE), Arg("START", "int32", TABLE),
                  Arg("COUNT", "int32", TABLE), Arg("MEMBERS", "int32", TABLE), Arg("UCOUNT", "int32", 1),
                  Arg("W", "uint32", EXPERTS * n * k // 8, 3), Arg("S", "bfloat16", EXPERTS * n * k // GROUP, 3),
                  Arg("B", "bfloat16", EXPERTS * n * k // GROUP, 3)]
        outputs = [Arg("ACT" if kind == "up" else "Y", "bfloat16", 64)]
        template = [("K", k), ("N", n), ("GS", GROUP), ("RPS", rps), ("SG", SIMDGROUPS)] + extra
        fname, text = kernel_text(name, inputs, outputs, source, header, template)
        out.append({"file": f"nemotron_expert_{kind}.metal", "kind": kind, "function": fname, "text": text,
                    "k": k, "n": n, "rps": rps, "template": template})
    return out


def file_text(kernel: dict) -> str:
    return (f"// Generated by tools/zig/gen_nemotron_metal.py from rows.py ({kernel['kind']} projection); do not edit.\n"
            + PREAMBLE + strip_comments(kernel["text"]))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the written files are stale")
    args = ap.parse_args()
    stale = 0
    for kernel in kernels():
        path = OUT / kernel["file"]
        text = file_text(kernel)
        if args.check:
            if not path.is_file() or path.read_text() != text:
                print(f"stale: {path.relative_to(ROOT)}")
                stale += 1
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}: {kernel['function']}")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
