// Generated by tools/zig/gen_glm_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
#ifndef METAL_FUNC
#define METAL_FUNC inline __attribute__((__always_inline__))
#endif
namespace metal {
METAL_FUNC bfloat16_t abs(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_fabs(static_cast<float>(x), __METAL_MAYBE_FAST_MATH__)); }
METAL_FUNC bfloat16_t exp(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_exp(static_cast<float>(x), __METAL_MAYBE_FAST_MATH__)); }
namespace fast {
METAL_FUNC bfloat16_t abs(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_fabs(static_cast<float>(x), __METAL_FAST_MATH__)); }
METAL_FUNC bfloat16_t exp(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_exp(static_cast<float>(x), __METAL_FAST_MATH__)); }
}
namespace precise {
METAL_FUNC bfloat16_t abs(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_fabs(static_cast<float>(x), __METAL_PRECISE_MATH__)); }
METAL_FUNC bfloat16_t exp(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_exp(static_cast<float>(x), __METAL_PRECISE_MATH__)); }
}
}

inline float load16(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
inline float qdot16(const device uint8_t* w, const thread float* xt, float scale, float bias, float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}

inline float bfsum4(const device bfloat* x) {
  return float(bfloat(float(bfloat(float(bfloat(float(x[0]) + float(x[1]))) + float(x[2]))) + float(x[3])));
}
inline float bfsum8(const device bfloat* x) {
  bfloat s = bfloat(float(x[0]) + float(x[1]));
  s = bfloat(float(s) + float(x[2])); s = bfloat(float(s) + float(x[3])); s = bfloat(float(s) + float(x[4]));
  s = bfloat(float(s) + float(x[5])); s = bfloat(float(s) + float(x[6])); s = bfloat(float(s) + float(x[7]));
  return float(s);
}
template <int B, int V> inline float loadv(const device bfloat* x, thread float* xt);
template <> inline float loadv<4, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
template <> inline float loadv<8, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 32>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 32; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<6, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i += 4) {
    sum += bfsum4(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 64.0f; xt[i + 2] = float(x[i + 2]) / 16.0f;
    xt[i + 3] = float(x[i + 3]) / 4.0f;
  }
  return sum;
}
template <> inline float loadv<5, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 8) {
    sum += bfsum8(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 32.0f; xt[i + 2] = float(x[i + 2]) / 4.0f;
    xt[i + 3] = float(x[i + 3]) / 128.0f; xt[i + 4] = float(x[i + 4]) / 16.0f; xt[i + 5] = float(x[i + 5]) / 2.0f;
    xt[i + 6] = float(x[i + 6]) / 64.0f; xt[i + 7] = float(x[i + 7]) / 8.0f;
  }
  return sum;
}
template <int B, int V> inline float qdotv(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                           float sum);
template <> inline float qdotv<4, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 8; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 16; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 32>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 32; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<6, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 4 * i;
    w += 3 * i;
    accum += (w[0] & 0x3f) * xt[0];
    accum += (w[0] & 0xc0) * xt[1];
    accum += (w[1] & 0x0f) * (xt[1] * 256.0f);
    accum += (w[1] & 0xf0) * xt[2];
    accum += (w[2] & 0x03) * (xt[2] * 256.0f);
    accum += (w[2] & 0xfc) * xt[3];
  }
  return scale * accum + sum * bias;
}
template <> inline float qdotv<5, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 8 * i;
    w += 5 * i;
    accum += (w[0] & 0x1f) * xt[0];
    accum += (w[0] & 0xe0) * xt[1];
    accum += (w[1] & 0x3) * (xt[1] * 256.0f);
    accum += (w[1] & 0x7c) * xt[2];
    accum += (w[1] & 0x80) * xt[3];
    accum += (w[2] & 0xf) * (xt[3] * 256.0f);
    accum += (w[2] & 0xf0) * xt[4];
    accum += (w[3] & 0x1) * (xt[4] * 256.0f);
    accum += (w[3] & 0x3e) * xt[5];
    accum += (w[3] & 0xc0) * xt[6];
    accum += (w[4] & 0x7) * (xt[6] * 256.0f);
    accum += (w[4] & 0xf8) * xt[7];
  }
  return scale * accum + sum * bias;
}

template <typename U>
inline U sigmoid_precise(U x) {
  U e = static_cast<U>(metal::precise::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
template <typename U>
inline U sigmoid_fast(U x) {
  U e = static_cast<U>(metal::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
#pragma clang fp contract(off)
template <int FMA>
inline float sq_acc(float acc, float v) { return FMA ? fma(v, v, acc) : v * v + acc; }
inline float mul_add(float acc, float a, float b) { return a * b + acc; }
inline float add_nc(float a, float b) { return a + b; }
#pragma clang fp contract(on)
template <int D, int U>
[[kernel]] void custom_kernel_tf_glm5_fused_hc_mix_packed_94dfb788d3__4096_8_bfloat16_t_float_bfloat16_t_float(
  const device bfloat16_t* X [[buffer(0)]],
  const device float* INV [[buffer(1)]],
  const device bfloat16_t* FNP [[buffer(2)]],
  device float* MIXES [[buffer(3)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  constexpr int S = 4;
  constexpr int F = S * D;
  constexpr int MIX = (2 + S) * S;

  const int og = int(threadgroup_position_in_grid.x);
  const int r = int(threadgroup_position_in_grid.y);
  const uint lane = thread_index_in_simdgroup, sgn = simdgroup_index_in_threadgroup;
  constexpr int ITERS = F / 1024;
  threadgroup float part[8][4];
  const float inv = INV[r];
  device const bfloat* xs = X + size_t(r) * F;
  const device uint4* w = (const device uint4*)(FNP + ((size_t(og) * 8 + sgn) * 32 + lane) * ITERS * 16);
  const int bn0 = (32 * int(sgn) + int(lane)) * 4;
  float res[4] = {0.0f, 0.0f, 0.0f, 0.0f};
  for (int i0 = 0; i0 < ITERS; i0 += U) {
    uint4 raw[U][2];
    float xv[U][4];
    for (int u = 0; u < U; u++) {
      raw[u][0] = w[(i0 + u) * 2]; raw[u][1] = w[(i0 + u) * 2 + 1];
      for (int tn = 0; tn < 4; tn++) xv[u][tn] = float(xs[bn0 + 1024 * (i0 + u) + tn]);
    }
    for (int u = 0; u < U; u++) {
      float vc[4];
      for (int tn = 0; tn < 4; tn++) vc[tn] = xv[u][tn] * inv;
      float inter[4][4];
      for (int h = 0; h < 2; h++) {
        const uint4 v = raw[u][h];
        const uint words[4] = {v.x, v.y, v.z, v.w};
        for (int j = 0; j < 4; j++) {
          const int e = h * 8 + j * 2;
          inter[e / 4][e % 4] = as_type<float>(words[j] << 16);
          inter[(e + 1) / 4][(e + 1) % 4] = as_type<float>(words[j] & 0xffff0000u);
        }
      }
      for (int tm = 0; tm < 4; tm++)
        for (int tn = 0; tn < 4; tn++) res[tm] += inter[tm][tn] * vc[tn];
    }
  }
  for (int tm = 0; tm < 4; tm++)
    for (ushort sn = 16; sn >= 1; sn >>= 1) res[tm] += simd_shuffle_down(res[tm], sn);
  if (lane == 0) for (int tm = 0; tm < 4; tm++) part[sgn][tm] = res[tm];
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (sgn == 0 && lane < 4) {
    float a = part[0][lane];
    for (int k = 1; k < 8; k++) a += part[k][lane];
    MIXES[r * MIX + og * 4 + lane] = a;
  }

}

template [[host_name("custom_kernel_tf_glm5_fused_hc_mix_packed_94dfb788d3__4096_8_bfloat16_t_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_hc_mix_packed_94dfb788d3__4096_8_bfloat16_t_float_bfloat16_t_float<4096, 8>) custom_kernel_tf_glm5_fused_hc_mix_packed_94dfb788d3__4096_8_bfloat16_t_float_bfloat16_t_float<4096, 8>;
