// Generated by tools/zig/gen_glm_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
#ifndef METAL_FUNC
#define METAL_FUNC inline __attribute__((__always_inline__))
#endif
namespace metal {
METAL_FUNC bfloat16_t abs(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_fabs(static_cast<float>(x), __METAL_MAYBE_FAST_MATH__)); }
METAL_FUNC bfloat16_t exp(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_exp(static_cast<float>(x), __METAL_MAYBE_FAST_MATH__)); }
namespace fast {
METAL_FUNC bfloat16_t abs(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_fabs(static_cast<float>(x), __METAL_FAST_MATH__)); }
METAL_FUNC bfloat16_t exp(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_exp(static_cast<float>(x), __METAL_FAST_MATH__)); }
}
namespace precise {
METAL_FUNC bfloat16_t abs(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_fabs(static_cast<float>(x), __METAL_PRECISE_MATH__)); }
METAL_FUNC bfloat16_t exp(bfloat16_t x) { return static_cast<bfloat16_t>(__metal_exp(static_cast<float>(x), __METAL_PRECISE_MATH__)); }
}
}

inline float load16(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
inline float qdot16(const device uint8_t* w, const thread float* xt, float scale, float bias, float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}

inline float bfsum4(const device bfloat* x) {
  return float(bfloat(float(bfloat(float(bfloat(float(x[0]) + float(x[1]))) + float(x[2]))) + float(x[3])));
}
inline float bfsum8(const device bfloat* x) {
  bfloat s = bfloat(float(x[0]) + float(x[1]));
  s = bfloat(float(s) + float(x[2])); s = bfloat(float(s) + float(x[3])); s = bfloat(float(s) + float(x[4]));
  s = bfloat(float(s) + float(x[5])); s = bfloat(float(s) + float(x[6])); s = bfloat(float(s) + float(x[7]));
  return float(s);
}
template <int B, int V> inline float loadv(const device bfloat* x, thread float* xt);
template <> inline float loadv<4, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
template <> inline float loadv<8, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 32>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 32; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<6, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i += 4) {
    sum += bfsum4(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 64.0f; xt[i + 2] = float(x[i + 2]) / 16.0f;
    xt[i + 3] = float(x[i + 3]) / 4.0f;
  }
  return sum;
}
template <> inline float loadv<5, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 8) {
    sum += bfsum8(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 32.0f; xt[i + 2] = float(x[i + 2]) / 4.0f;
    xt[i + 3] = float(x[i + 3]) / 128.0f; xt[i + 4] = float(x[i + 4]) / 16.0f; xt[i + 5] = float(x[i + 5]) / 2.0f;
    xt[i + 6] = float(x[i + 6]) / 64.0f; xt[i + 7] = float(x[i + 7]) / 8.0f;
  }
  return sum;
}
template <int B, int V> inline float qdotv(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                           float sum);
template <> inline float qdotv<4, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 8; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 16; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 32>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 32; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<6, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 4 * i;
    w += 3 * i;
    accum += (w[0] & 0x3f) * xt[0];
    accum += (w[0] & 0xc0) * xt[1];
    accum += (w[1] & 0x0f) * (xt[1] * 256.0f);
    accum += (w[1] & 0xf0) * xt[2];
    accum += (w[2] & 0x03) * (xt[2] * 256.0f);
    accum += (w[2] & 0xfc) * xt[3];
  }
  return scale * accum + sum * bias;
}
template <> inline float qdotv<5, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 8 * i;
    w += 5 * i;
    accum += (w[0] & 0x1f) * xt[0];
    accum += (w[0] & 0xe0) * xt[1];
    accum += (w[1] & 0x3) * (xt[1] * 256.0f);
    accum += (w[1] & 0x7c) * xt[2];
    accum += (w[1] & 0x80) * xt[3];
    accum += (w[2] & 0xf) * (xt[3] * 256.0f);
    accum += (w[2] & 0xf0) * xt[4];
    accum += (w[3] & 0x1) * (xt[4] * 256.0f);
    accum += (w[3] & 0x3e) * xt[5];
    accum += (w[3] & 0xc0) * xt[6];
    accum += (w[4] & 0x7) * (xt[6] * 256.0f);
    accum += (w[4] & 0xf8) * xt[7];
  }
  return scale * accum + sum * bias;
}

template <typename U>
inline U sigmoid_precise(U x) {
  U e = static_cast<U>(metal::precise::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
template <typename U>
inline U sigmoid_fast(U x) {
  U e = static_cast<U>(metal::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
#pragma clang fp contract(off)
template <int FMA>
inline float sq_acc(float acc, float v) { return FMA ? fma(v, v, acc) : v * v + acc; }
inline float mul_add(float acc, float a, float b) { return a * b + acc; }
inline float add_nc(float a, float b) { return a + b; }
#pragma clang fp contract(on)
template <int D, int SQ_FMA, int ITERS, int HC_EPS_INT>
[[kernel]] void custom_kernel_tf_glm5_fused_hc_split_norm_4dfd80f94d__4096_0_20_1000_bfloat16_t_float_floatc_float_bfloat16_t_floatc_bfloat16_t_float_float(
  const device bfloat16_t* X [[buffer(0)]],
  const device float* MIXES [[buffer(1)]],
  const constant float* SCALE [[buffer(2)]],
  const device float* BASEV [[buffer(3)]],
  const device bfloat16_t* NORMW [[buffer(4)]],
  const constant float* EPS [[buffer(5)]],
  device bfloat16_t* NORMED [[buffer(6)]],
  device float* POST_OUT [[buffer(7)]],
  device float* COMB_OUT [[buffer(8)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  constexpr int S = 4;
  constexpr int F = S * D;
  constexpr int MIX = (2 + S) * S;

  constexpr float HC_EPS = HC_EPS_INT * 1e-9;
  const int r = int(threadgroup_position_in_grid.x);
  const uint t = thread_position_in_threadgroup.x;
  const uint lane = thread_index_in_simdgroup, sg = simdgroup_index_in_threadgroup;
  threadgroup float red[32];
  threadgroup float pre_s[S];
  threadgroup float inv_s[1];
  device const float* mixes = MIXES + r * MIX;
  device const bfloat* xs = X + size_t(r) * F;
  if (sg == 0) {
    constexpr int BASE_OFF = 2 * S;
    const float pre_scale = SCALE[0], post_scale = SCALE[1], comb_scale = SCALE[2];
    const float active = (lane < (uint)S) ? 1.0f : 0.0f;
    const uint llane = metal::min(lane, (uint)(S - 1));
    const float pre_z = mixes[llane] * pre_scale + BASEV[llane];
    const float post_z = mixes[S + llane] * post_scale + BASEV[S + llane];
    const float pre_v = 1.0f / (1.0f + metal::fast::exp(-pre_z)) + HC_EPS;
    const float post_v = 2.0f / (1.0f + metal::fast::exp(-post_z));
    if (lane < (uint)S) { pre_s[lane] = pre_v; POST_OUT[r * S + lane] = post_v; }
    float4 v = (*(const device float4*)(mixes + BASE_OFF + llane * S) * comb_scale
                + *(const device float4*)(BASEV + BASE_OFF + llane * S)) * active;
    const float row_max = metal::max(metal::max(v.x, v.y), metal::max(v.z, v.w));
    const float4 e = metal::fast::exp(v - row_max) * active;
    float4 rr = e * (1.0f / (e.x + e.y + e.z + e.w + HC_EPS)) + HC_EPS * active;
    float4 col_inv = 1.0f / (float4(simd_sum(rr.x), simd_sum(rr.y), simd_sum(rr.z), simd_sum(rr.w)) + HC_EPS);
    rr *= col_inv;
    for (int iter = 1; iter < ITERS; ++iter) {
      rr *= (1.0f / (rr.x + rr.y + rr.z + rr.w + HC_EPS)) * active;
      col_inv = 1.0f / (float4(simd_sum(rr.x), simd_sum(rr.y), simd_sum(rr.z), simd_sum(rr.w)) + HC_EPS);
      rr *= col_inv;
    }
    if (lane < (uint)S) *(device float4*)(COMB_OUT + r * S * S + lane * S) = rr;
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  const float p0 = pre_s[0], p1 = pre_s[1], p2 = pre_s[2], p3 = pre_s[3];
  float xc[4];
  float acc = 0.0f;
  for (int i = 0; i < 4; ++i) {
    const int d = int(t) * 4 + i;
    const float res = fma(p0, float(xs[d]), fma(p1, float(xs[D + d]),
                          fma(p2, float(xs[2 * D + d]), p3 * float(xs[3 * D + d]))));
    xc[i] = float(bfloat(res));
    acc = sq_acc<SQ_FMA>(acc, xc[i]);
  }
  acc = simd_sum(acc);
  if (sg == 0) red[lane] = 0.0f;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (lane == 0) red[sg] = acc;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (sg == 0) {
    const float a = simd_sum(red[lane]);
    if (lane == 0) inv_s[0] = metal::precise::rsqrt(a / float(D) + EPS[0]);
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  for (int i = 0; i < 4; ++i) {
    const int d = int(t) * 4 + i;
    NORMED[size_t(r) * D + d] = NORMW[d] * bfloat(xc[i] * inv_s[0]);
  }

}

template [[host_name("custom_kernel_tf_glm5_fused_hc_split_norm_4dfd80f94d__4096_0_20_1000_bfloat16_t_float_floatc_float_bfloat16_t_floatc_bfloat16_t_float_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_hc_split_norm_4dfd80f94d__4096_0_20_1000_bfloat16_t_float_floatc_float_bfloat16_t_floatc_bfloat16_t_float_float<4096, 0, 20, 1000>) custom_kernel_tf_glm5_fused_hc_split_norm_4dfd80f94d__4096_0_20_1000_bfloat16_t_float_floatc_float_bfloat16_t_floatc_bfloat16_t_float_float<4096, 0, 20, 1000>;
